# Generated by Django 5.2.17 on 2026-09-09 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_summary_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_summary_request',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'date_from', 'date_to', 'payload_hash'], name='ix_ai_summary_dedup')],
            },
        ),
    ]
